#INspired by sb-local-development/local/sb-swip-middleware.yaml
sb-swip-middleware:
  # Create secrets for MongoDB and PostgreSQL?????
  # Release:
  #   IsInstall: 
  #     enabled: true
  # secrets:
  #   # MongoDB credentials
  #   mongodb:
  #     create: true
  #     data:
  #       username: root
  #       password: password
    
  #   # PostgreSQL credentials
  #   postgresql:
  #     create: true
  #     data:
  #       postgres-password: postgres
  #       password: postgres
  #       username: postgres

  cloudnativepg:
    enabled: true
    host: swim-rw.cloud-pg
    port: 5432
    user: postgres
    password: postgres
  
  postgresql:
    enabled: false
    # auth:
    #   existingSecret: swip-middleware-postgresql
    #   secretKeys:
    #     adminPasswordKey: postgres
    #     userPasswordKey: password
    # service:
    #   type: LoadBalancer
    # persistence:
    #   enabled: true
    #   size: 1Gi #change size?? orginal 10Gi
    #   storageClass: local-path 

  postgresql-ha:
    enabled: false

  mongodb:
    enabled: true
    # auth:
    #   existingSecret: mongodb-credentials
    #   userKey: username
    #   passwordKey: password
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi #testa större size? orginal 8Gi
      
  sb-kafka:
    enabled: true
    kafka:
      enabled: true
      service:
        type: LoadBalancer  

  cp-helm-charts:
    enabled: false
  
  sb-schema-registry:
    enabled: false  

