#INspired by sb-local-development/local/sb-swip-middleware.yaml
sb-swip-middleware:

  cloudnativepg:
    enabled: false
    host: swim-rw.cloud-pg
    port: 5432
    user: postgres
    service:
      type: LoadBalancer
    
  postgresql:
    enabled: true
    service:
      type: LoadBalancer
    primary:
      initdb:
        scripts:
          create-databases.sql: |
            CREATE DATABASE sb_parties;
            CREATE DATABASE sb_authorization;
    auth:
      postgresPassword: ""  # Let Helm manage the password
    persistence:
      size: 1Gi

  postgresql-ha:
    enabled: false

  sb-kafka:
    enabled: true
    kafka:
      enabled: true
      service:
        type: LoadBalancer  

  mongodb:
    enabled: true
    # auth:
    #   existingSecret: mongodb-credentials
    #   userKey: username
    #   passwordKey: password
    service:
      type: LoadBalancer
    persistence:
      size: 1Gi #testa större size? orginal 8Gi

  cp-helm-charts:
    enabled: false
    cp-kafka:
      enabled: false
    cp-zookeeper:
      enabled: false

  sb-schema-registry:
    enabled: false  

