#INspired by sb-local-development/local/sb-swip-middleware.yaml
sb-swip-middleware:

  cloudnativepg:
    enabled: false
    # host: swim-rw.cloud-pg
    # port: 5432
    # user: postgres
    # service:
    #   type: LoadBalancer
    
  postgresql:
    enabled: true
    persistence:
      storageClass: local-path
      size: 1Gi

  mongodb:
    enabled: true
    persistence:
      storageClass: local-path
      size: 1Gi #testa större size? orginal 8Gi

  cp-helm-charts:
    enabled: true
    cp-kafka:
      persistence:
        storageClass: local-path
        size: 1Gi
    cp-zookeeper:
      persistence:
        dataDirSize: 1Gi
        dataDirStorageClass: local-path
        dataLogDirSize: 1Gi
    cp-schema-registry:
      enabled: true
