#INspired by sb-local-development/local/sb-swip-middleware.yaml
sb-swip-middleware:
  #dbInit:
  #  enabled: false 
  cloudnativepg:
    enabled: false
    host: swim-rw.cloud-pg
    user: postgres
    port: 5432
    service:
      type: LoadBalancer
  
  postgresql:
    enabled: true
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 1Gi #change size?? orginal 10Gi
      storageClass: local-path
 
  postgresql-ha:
    enabled: false

  mongodb:
    enabled: true
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi #testa större size? orginal 8Gi
      
  sb-kafka:
    enabled: true

  cp-helm-charts:
    enabled: false


  # cluster:
  #   fullnameOverride: "swim"
  #   type: postgresql
  #   version:
  #     postgresql: "17"

  #   cluster:
  #     instances: 1
  #     imageName: ghcr.io/cloudnative-pg/postgresql:17.0-17
  #     imagePullPolicy: IfNotPresent

  #     primaryUpdateStrategy: unsupervised

  #     enableSuperuserAccess: true
  #     superuserSecret: cloudnativepg
      
  #     storage:
  #       size: 2Gi
  #       storageClass: local-path

  #     monitoring:
  #       enabled: false

  #     postgresql:
  #       parameters:
  #         password_encryption: md5
  #       pg_hba:
  #         - host all all all md5
  #         - host all all 0.0.0.0/0 md5

  #   backups:
  #     enabled: false