#INspired by sb-local-development/local/sb-swip-middleware.yaml
sb-swip-middleware:
  # Create secrets for MongoDB
  secrets:
    mongodb:
      create: true
      data:
        username: root
        password: password
    
    # PostgreSQL credentials
    postgresql:
      create: true
      data:
        postgres-password: postgres
        password: postgres
        username: postgres

  cloudnativepg:
    enabled: false
    host: swim-rw.cloud-pg
    user: postgres
    port: 5432
    service:
      type: LoadBalancer
  
  postgresql:
    enabled: true
    auth:
      existingSecret: swip-middleware-postgresql
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 1Gi #change size?? orginal 10Gi
      storageClass: local-path
 
  postgresql-ha:
    enabled: false

  mongodb:
    enabled: true
    auth:
      existingSecret: mongodb-credentials
      userKey: username
      passwordKey: password
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi #testa större size? orginal 8Gi
      
  sb-kafka:
    enabled: true
    kafka:
      enabled: true
      service:
        type: LoadBalancer  

  cp-helm-charts:
    enabled: false

