apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swip-middleware
  namespace: argocd
spec:
  project: default
  destination:
    namespace: local
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/elski569/swip-deployment/
    path: helm/middleware-wrapper
    targetRevision: HEAD
    helm:
      skipCrds: false
      valueFiles:
            - 'values.yaml' 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: batch
    kind: Job
    name: db-init-job
    jsonPointers:
    - /status
    - /spec/selector
    - /spec/template/spec
