apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elsa-mw
  namespace: argocd
spec:
  project: default
  destination:
    namespace: local
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/elski569/swip-deployment.git
    path: helm/middleware-wrapper
    targetRevision: HEAD
    helm:
      skipCrds: false
      valueFiles:
            - 'values.yaml' 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
