sb-swip-platform:
  # Admin Service configuration
  # From manual setup: "The admin service is required to set up users, and getting data for them"
  sb-admin-service:
    enabled: true
    cloudnativepg:
      enabled: true
      host: swim-restore-rw.cloud-pg
    config:
      swimbird:
        authorization:
          keycloak:
            # Keycloak configuration matching manual setup
            baseUri: http://keycloak.keycloak:8090
            baseUris: http://keycloak.keycloak:8090
    image:
      tag: latest
      imagePullPolicy: Always
    tracing:
      enabled: false

  #maybe not necessary  
  sb-private-assets:
    image:
      tag: latest
      imagePullPolicy: Always
    enabled: false

  #maybe not necessary  
  sb-private-funds: 
    enabled: false
    image:
      tag: latest
      imagePullPolicy: Always

  # Standalone Service configuration
  # From manual setup: "Standalone is our backend service, which is a very big piece of software"
  sb-standalone:
    enabled: true
    config:
      sb_services:
        authorization:
          keycloak:
            # Keycloak configuration matching manual setup port forwards
            hostName: keycloak.keycloak
            adminPort: 8090
            clientPort: 8090
        marketdata:
          elastic:
            host: elasticsearch-master.shared
        featureFlags:
          useStrimziKafka: true
        layout:
          profile_path: value-bridge
        # MongoDB configuration matching manual setup
        mongodb:
          username: root
          password: password
          authentication-database: admin
          port: 27017
    cloudnativepg:
      enabled: true
      host: swim-restore-rw.cloud-pg
    image:
      tag: latest
      imagePullPolicy: Always
    tracing:
      enabled: false
    cache:
      redis:
        # standalone-cache-test in GCP
        host: 10.78.254.203
  sb-swip-app:
    enabled: true
    image:
      tag: latest
      imagePullPolicy: Always
    config:
      USE_LEGACY_ACCOUNT_LIST: "false"
      RESTRICT_DASHBOARD_CHART_VIEW: "false"
      # Backend URLs matching the proxy.config.js setup from manual instructions
      BACKEND_URL: "http://sb-standalone:8080"
      ADMIN_BACKEND_URL: "http://sb-admin-service:7001"
  sb-accounting:
    enabled: false
    config:
      swimbird:
        authorization:
          keycloak:
            baseUri: http://keycloak.keycloak:8090
    cloudnativepg:
      enabled: true
      host: swim-restore-rw.cloud-pg
    image:
      tag: latest
      imagePullPolicy: Always
    tracing:
      enabled: false
  sb-document:
    enabled: false
    image:
      tag: latest
    cloudnativepg:
      enabled: true
      host: swim-restore-rw.cloud-pg
    storage:
      bucketname: swimbird-test-document-service-assets
    tracing:
      enabled: false
  sb-clickhouse-interface:
    enabled: false
    image:
      tag: latest
    database:
      host: bbe5ik2wva.europe-west4.gcp.clickhouse.cloud
  sb-clickhouse-cdc:
    enabled: false
    image:
      tag: latest
    cloudnativepg:
      enabled: true
      host: swim-restore-rw.cloud-pg
    clickhouse:
      host: bbe5ik2wva.europe-west4.gcp.clickhouse.cloud
  sb-config-provider:
    enabled: true
    
  # Note: All storage classes are set to local-path as mentioned in manual setup:
  # "The storage class for persistence in the middleware is set to local-path.
  # This is one of the CRDs we installed earlier, which is used by Rancher
  # to set up storage for databases and the like on local machines."