#INspired by sb-local-development/local/sb-swip-platform.yaml
sb-swip-platform:
  global:
    ingress:
      enabled: false
  
  sb-admin-service:
    enabled: true
    cloudnativepg:
      enabled: false # funkar ej
    config:
      swimbird:
        authorization:
          keycloak:
            baseUri: http://keycloak.keycloak:8090 #ns.service:port
            baseUris: http://keycloak.keycloak:8090
    #image:
    #  tag: latest
    #  imagePullPolicy: Always
    #tracing:
    #  enabled: false
    postgres:
      host: swip-middleware-postgresql  # Point to existing PostgreSQL service
      port: 5432
      partiesDatabase: sb_parties
      authorizationDatabase: sb_authorization
      # Remove the middleware.suffix setting
      middleware:
        suffix: ""  # Empty string to prevent adding -mw
      # Remove any release name prefix
      fullnameOverride: swip-middleware-postgresql
      releaseName: "" 

    # Spring configuration
    env:
      - name: SPRING_DATASOURCE_PARTIES_URL
        value: "jdbc:postgresql://swip-middleware-postgresql:5432/sb_parties"
      - name: SPRING_DATASOURCE_AUTHORIZATION_URL
        value: "jdbc:postgresql://swip-middleware-postgresql:5432/sb_authorization"
      - name: SPRING_DATASOURCE_PARTIES_USERNAME
        value: postgres
      - name: SPRING_DATASOURCE_AUTHORIZATION_USERNAME
        value: postgres

    service:
      type: LoadBalancer

  sb-private-assets:
    enabled: false #bra för test
    image:
      tag: latest
      imagePullPolicy: Always
  
  sb-private-funds: 
    enabled: false
    image:
      tag: latest
      imagePullPolicy: Always

  sb-standalone:
    enabled: true
    resources:
      default: small
    ingress:
      enabled: false
    config:
      # sb_services:
      #   authorization:
      #     keycloak:
      #       hostName: keycloak.keycloak
      #       adminPort: 8090
      #       clientPort: 8090
      #   marketdata:
      #     elastic:
      #       host: elasticsearch-master.shared
      #   featureFlags:
      #     useStrimziKafka: true
      #   layout:
      #       profile_path: value-bridge
      sb_services:
        authorization:
          oauth2:
            realm: local
            clientSecret: u4EHBMgAum9dU1a9ohSi6DWsMdimBz3j
          keycloak:
            hostName: localhost
            port: 8090
          swip_app:
            host: localhost
            port: 8090
        layout:
          profile_path: value-bridge
        liveness:
          enabled: false
          failureThreshold: 100
          periodSeconds: 300
          initialDelaySeconds: 300
        readiness:
          enabled: false
          failureThreshold: 100
          periodSeconds: 300
          initialDelaySeconds: 300
    cloudnativepg:
      enabled: false
    image:
      tag: latest
      imagePullPolicy: Always
    sb-kafka:
      enabled: true
      releaseName: local-mw
      cloud:
        enabled: false
    mongodb:
      releaseName: local-mw
    tracing:
      enabled: false
    cache:
      redis:
        # standalone-cache-test in GCP
        host: 10.78.254.203
    monitoring:
      enabled: false
    service:
      port: 8093
      type: LoadBalancer
    probes:
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false

  sb-swip-app :
    enabled: true
    image:
      tag: latest
      imagePullPolicy: Always
    ingress:
      enabled: false
    service:
      port: 8090
      type: LoadBalancer
    config:
      backendPort: 8093
      peFundsBackendPort: 8091
      privateAssetsBackendPort: 8092
      USE_GLOBAL_ACCOUNT_SELECTOR_REPLACE: true
      globalResourceBasePath:
      USE_LEGACY_ACCOUNT_LIST: "false"
      RESTRICT_DASHBOARD_CHART_VIEW: "false"
    
  sb-accounting:
    enabled: false
    # config:
    #   swimbird:
    #     authorization:
    #       keycloak:
    #         baseUri: http://keycloak.keycloak:8090
    # cloudnativepg:
    #   enabled: false
    #   host: swim-restore-rw.cloud-pg
    # image:
    #   tag: latest
    #   imagePullPolicy: Always
    # tracing:
    #   enabled: false
  
  sb-document:
    enabled: false
    # image:
    #   tag: latest
    # cloudnativepg:
    #   enabled: true
    #   host: swim-restore-rw.cloud-pg
    # storage:
    #   bucketname: swimbird-test-document-service-assets
    # tracing:
    #   enabled: false
  
  sb-clickhouse-interface:
    enabled: false
    # image:
    #   tag: latest
    # database:
    #   host: bbe5ik2wva.europe-west4.gcp.clickhouse.cloud
  
  sb-clickhouse-cdc:
    enabled: false
    # image:
    #   tag: latest
    # cloudnativepg:
    #   enabled: true
    #   host: swim-restore-rw.cloud-pg
    # clickhouse:
    #   host: bbe5ik2wva.europe-west4.gcp.clickhouse.cloud
  
  sb-config-provider:
    enabled: false

  service:
    type: LoadBalancer

